[build]
builder = "nixpacks"
builderSettings = { nixpacks = { config = { installStage = { aptPackages = ["ffmpeg", "libsndfile1"] } } } }

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
startCommand = "python bot.py"

[variables]
BOT_TOKEN = "xxxxxxx"
PORT = "3000"
PYTHON_VERSION = "3.12"
MAX_AUDIO_DURATION = "60"
DEBUG = "false"
